export const creepConfig = {
  // harvest
  HARVEST_CREEP_ROLE: "Harvester",
  HARVEST_CREEP_PRIORITY: 8,
  HARVEST_CREEP_REPLACE_TTL: 20,
  HARVEST_CREEP_BODY: [
    [MOVE, WORK, WORK],
    [MOVE, WORK, WORK, WORK, WORK, WORK],
    [MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK] // energy = 750
  ],
  HARVEST_CREEP_BODY_COST: [250, 550, 750],

  // upgrade
  UPGRADE_CREEP_ROLE: "Upgrader",
  UPGRADE_CREEP_PRIORITY: 2,
  UPGRADE_CREEP_BODY: [
    [MOVE, MOVE, WORK, CARRY, CARRY],
    [MOVE, MOVE, WORK, WORK, CARRY, CARRY],
    [MOVE, MOVE, MOVE, WORK, WORK, WORK, CARRY, CARRY],
    [MOVE, MOVE, MOVE, MOVE, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY] // energy = 700
  ],
  UPGRADE_CREEP_BODY_COST: [300, 400, 550, 700],
  UPGRADE_CREEP_LIMIT: [0, 5, 5, 5, 5, 5, 5, 5, 1],

  // express
  EXPRESS_CREEP_ROLE: "Express",
  EXPRESS_CREEP_PRIORITY: 5,
  EXPRESS_CREEP_BODY: [
    [MOVE, MOVE, MOVE, CARRY, CARRY, CARRY],
    [MOVE, MOVE, MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY],
    [
      // eslint-disable-next-line prettier/prettier
      MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE,
      // eslint-disable-next-line prettier/prettier
      CARRY, CARRY,CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY
    ] // energy = 900
  ],
  EXPRESS_CREEP_BODY_COST: [300, 500, 900],

  // construct
  // construct
  CONSTRUCT_CREEP_ROLE: "Construct",
  CONSTRUCT_CREEP_PRIORITY: 5,
  CONSTRUCT_CREEP_BODY: [
    [MOVE, MOVE, CARRY, CARRY, WORK],
    [MOVE, MOVE, CARRY, CARRY, CARRY, WORK, WORK, WORK],
    [MOVE, MOVE, MOVE, CARRY, CARRY, CARRY, CARRY, CARRY, WORK, WORK, WORK, WORK, WORK] // energy = 900
  ],
  CONSTRUCT_CREEP_BODY_COST: [300, 550, 900],
  CONSTRUCT_CREEP_NUM: [0, 1, 2, 3, 4, 5, 5, 5, 5]
};

export enum HARVEST_CREEP_STATE {
  STATE_INIT,
  STATE_WORK,
  STATE_SUICIDE = -1 // creep will suicide after 1. pass source to spawn 2. receive suicide instruction from other creep
}

export enum UPGRADE_CREEP_STATE {
  STATE_INIT,
  STATE_WORK,
  STATE_SUICIDE = -1
}

export enum EXPRESS_CREEP_STATE {
  STATE_INIT,
  STATE_IDLE,
  STATE_FETCH,
  STATE_CARRY
}

export enum CONSTRUCT_CREEP_STATE {
  STATE_INIT,
  STATE_IDLE,
  STATE_FETCH,
  STATE_WORK
}
